// <auto-generated />
using System;
using HospitalPatientManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalPatientManager.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("HospitalPatientManager.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 7, 30, 0, 0, DateTimeKind.Utc),
                            FullName = "Dr. Maya Putri",
                            Specialization = "Internal Medicine"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 10, 7, 35, 0, 0, DateTimeKind.Utc),
                            FullName = "Dr. Raka Wijaya",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 7, 40, 0, 0, DateTimeKind.Utc),
                            FullName = "Dr. Nanda Lestari",
                            Specialization = "Cardiology"
                        });
                });

            modelBuilder.Entity("HospitalPatientManager.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnosis = "Seasonal flu",
                            DoctorId = 1,
                            PatientId = 1,
                            VisitDate = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Diagnosis = "Hypertension",
                            DoctorId = 3,
                            PatientId = 2,
                            VisitDate = new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Diagnosis = "Mild asthma",
                            DoctorId = 2,
                            PatientId = 3,
                            VisitDate = new DateTime(2026, 1, 13, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Diagnosis = "Chest pain follow-up",
                            DoctorId = 3,
                            PatientId = 1,
                            VisitDate = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Diagnosis = "Gastritis",
                            DoctorId = 1,
                            PatientId = 2,
                            VisitDate = new DateTime(2026, 1, 15, 15, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HospitalPatientManager.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jakarta",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 5, 12),
                            FullName = "Budi Santoso",
                            Gender = "Male",
                            PhoneNumber = "081234567890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bandung",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 5, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 11, 3),
                            FullName = "Siti Rahma",
                            Gender = "Female",
                            PhoneNumber = "081298765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Surabaya",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 10, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2001, 2, 18),
                            FullName = "Andi Pratama",
                            Gender = "Male",
                            PhoneNumber = "081322233344"
                        });
                });

            modelBuilder.Entity("HospitalPatientManager.Models.MedicalRecord", b =>
                {
                    b.HasOne("HospitalPatientManager.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalPatientManager.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalPatientManager.Models.Doctor", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("HospitalPatientManager.Models.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
